# Mode serangan: aktif otomatis saat NightGuard mendeteksi DDoS.
limit_req zone=ng_strict burst=15 nodelay;
limit_req zone=ng_remote burst=100 nodelay;
limit_req zone=ng_login burst=2 nodelay;
limit_conn ng_conn 15;
